server:
  port: 8088

spring:
  application:
    name: 'micrometer'
#  sleuth:
#    log:
#      slf4j:
#        whitelisted-mdc-keys: traceId, spanId

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always

logging:
  file:
    name: '${logging.file.path}/app.log'
    path: ./logs
  pattern:
    level: "%5p [${spring.application.name:},%X{trace_id:-},%X{span_id:-}]"
    dateformat: yyyy-MM-dd HH:mm:ss.SSS
  logback:
    rollingpolicy:
      max-file-size: 1MB
      max-history: 5
      file-name-pattern: '${LOG_FILE}-%d{yyyy-MM-dd}.%i.log.gz'

camel:
  springboot:
    main-run-controller: true
  component:
    mdc-logging:
      enabled: true